#!/usr/bin/env bash
# Script for managing the manage_my_process
# Requirements:
# - Script displays manage_my_process started when started
# - Script displays manage_my_process stopped when stopped
# - Script displays manage_my_process restarted when restarted
# - Script displays Usage: manage_my_process {start|stop|restart} when nothing is passed or something different than start, stop, or restart
# - Script creates /var/run/my_process.pid file when started
# - Script starts manage_my_process process when started
# - Script deletes /var/run/my_process.pid file when stopped


PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
    if [ -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is already running."
    else
        ./manage_my_process >/dev/null 2>&1 &
        echo -n $! > "$PID_FILE"
	echo "$PROCESS_NAME started"
    fi
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "$PROCESS_NAME stopped"
    else
        echo "$PROCESS_NAME is not running."
	echo "Good"
    fi
}

restart_process() {
    if [ -f "$PID_FILE" ]; then
    fi
    echo "$PROCESS_NAME restarted"
    exit 0 
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	echo "Script delete $PID_FILE file when stopped" 
        echo "The script starts $PROCESS_NAME process when started"
        exit 1
        ;;
esac

exit 0
